version: "3.9"

services:
  app:
    container_name: hacktoberfest_issues-cont
    image: hacktoberfest_issues
    tty: true                                   # false for `entrypoint` in Dockerfile
    stdin_open: true                            # false for `entrypoint` in Dockerfile
    env_file:
      - .env
    # volumes:
    # - .:/app                                  # local development; interferes with node_modules
    # - ./logs:/root/.npm/                      # troubleshooting logs
    ports:
      - ${PORT:-3000}:3000
    build:
      context: ./
      dockerfile: ./Dockerfile
