name: Bug report
description: Seen an error or bug, notify and help us to resolve it.
title: "[BUG] - <description here>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "# Bug report"
  - type: textarea
    id: description
    attributes:
      label: What bug or error did you encounter?
      description: |
        Please give a detailed description of the bug.

        Include a description of what happened as well as the steps you took to cause the bug.
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: What did you expect to happen?
      description: What did you expect to happen instead of the current behaviour?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Attach any relevant screenshots here.
    validations:
      required: false
  - type: textarea
    id: additionalinformation
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: false
